#### Objectif :

Ce notebook met en place une seconde étape d'analyse, complémentaire au pipeline Morlet exploratoire.

L'idée générale est la suivante :

on utilise Morlet pour repérer de manière exploratoire les bandes et fenêtres fréquentielles potentiellement modulées ;
on revient ensuite au signal continu, que l'on filtre dans des sous-bandes fixes ;
on extrait l'enveloppe d'amplitude par transformée de Hilbert ;
on normalise cette enveloppe à l'échelle de la session ;
on époque autour des stimulations ;
on regroupe les observations par condition cognitive et localité (local / distant) ;
on teste ensuite les courbes temporelles Hilbert, session par session ou pooled across sessions.

Le découpage suit la logique méthodologique inspirée de Vidal et al. (2010), adaptée aux stimulations intracérébrales.

In [ ]:
# imports
from pathlib import Path
import pandas as pd
import json

from utils_time_frequency.lfp_hilbert_utils import (
    HilbertConfig,
    # build_hilbert_subbands,
    build_main_band_to_subbands,
    prepare_hilbert_session_data,
    run_session_hilbert,
    run_all_sessions_hilbert,
    load_hilbert_session_exports,
    load_hilbert_band_epochs,
)

from utils_time_frequency.lfp_hilbert_stats import (
    HilbertStatsConfig,
    stack_hilbert_band_condition_locality,
    stack_hilbert_band_condition_locality_across_sessions,
    run_hilbert_session_condition_stats,
    run_pooled_hilbert_condition_stats,
    run_all_hilbert_stats,
)

from utils_time_frequency.lfp_preprocess_utils import (
    list_trc_sessions,
    load_bad_channels_table,
)

from utils_time_frequency.lfp_morlet_stats import (
    build_main_condition_index,
    build_cog_subcategory_index,
)

#### Hilbert run

Structure de travail : 

root_dir/                                                                {= root_dir, dans HilbertConfig}
    └── results_hilbert/                                                 {= output_dir, dans HilbertConfig}
        └── PATIENT_stimN/                                               {créé}
            ├── PATIENT_stimN_metadata.json
            ├── PATIENT_stimN_trial_table.csv
            ├── PATIENT_stimN_times.npy
            └── PATIENT_stimN_hilbert_<band>.npy {theta, alpha, beta, low_gamma}
        ...
        └── run_summary_hilbert.json                                     {créé, quand run Hilbert}


    ├── PATIENT_stimN.TRC                                                 {nécessaire}
    ├── PATIENT_stimN_stim_events_TRC_corrected.txt                       {nécessaire, sinon créé}
    ├── PATIENT_stimN_stim_events_TRC_re-shifted_loca_COG.txt             {nécessaire}

    ou si pas de *_corrected.txt (normalement si, car on a deja run morlet sur cette session ?), alors besoin de :
    ├── PATIENT_stimN_stim_events_TRC.txt                                 {optionnel}
    ├── PATIENT_stimN_stim_sevents_TRC_shifted.txt                        {optionnel}
    ├── PATIENT_stimN_stim_events_TRC_re-shifted.txt                      {optionnel}
    ...
    └── TRC_bad_channels.xlsx                                             {nécessaire}

In [6]:
# configuration Hilbert

hilbert_cfg = HilbertConfig(
    root_dir="/home/aube/Documents/article_neuronal_stimic/effets_cog/LFP/theta_gamma_cog",
    output_dir="/home/aube/Documents/article_neuronal_stimic/effets_cog/LFP/theta_gamma_cog/results_hilbert",

    pre_length=3.0,
    post_length=3.0,
    epsilon=0.1,

    do_notch=True,
    notch_freqs=(50.0, 100.0, 150.0),
    notch_q=30.0,
    do_highpass=True,
    highpass_hz=0.1,

    gamma_low_hz=30.0,
    gamma_high_hz=150.0,
    gamma_step_hz=10.0,

    beta_low_hz = 12.0,
    beta_high_hz = 30.0,
    beta_step_hz = 4.0,

    alpha_low_hz = 8.0,
    alpha_high_hz = 12.0,
    alpha_step_hz = 2.0,

    theta_low_hz=4.0,
    theta_high_hz=8.0,
    theta_step_hz=2.0,

    include_delta=False,
    delta_low_hz=1.0,
    delta_high_hz=4.0,
    delta_step_hz=1.0,

    normalization_mode="pre_first_stim_mean",
    target_dt_ms=16.0,

    save_subband_epochs=False,
    save_main_band_epochs=True,
    verbose=True,
)

In [7]:
# inspection des sous-bandes Hilbert construites
main_band_map = build_main_band_to_subbands(hilbert_cfg)
main_band_map

{'theta': [('theta', 4.0, 6.0), ('theta', 6.0, 8.0)],
 'alpha': [('alpha', 8.0, 10.0), ('alpha', 10.0, 12.0)],
 'beta': [('beta', 12.0, 16.0),
  ('beta', 16.0, 20.0),
  ('beta', 20.0, 24.0),
  ('beta', 24.0, 28.0),
  ('beta', 28.0, 30.0)],
 'low_gamma': [('gamma', 30.0, 40.0),
  ('gamma', 40.0, 50.0),
  ('gamma', 50.0, 60.0),
  ('gamma', 60.0, 70.0),
  ('gamma', 70.0, 80.0)],
 'high_gamma': [('gamma', 80.0, 90.0),
  ('gamma', 90.0, 100.0),
  ('gamma', 100.0, 110.0),
  ('gamma', 110.0, 120.0),
  ('gamma', 120.0, 130.0),
  ('gamma', 130.0, 140.0),
  ('gamma', 140.0, 150.0)]}

In [8]:
# sessions disponibles
root_dir = Path(hilbert_cfg.root_dir)
sessions = list_trc_sessions(root_dir)
print(f"{len(sessions)} sessions trouvées")
sessions

1 sessions trouvées

['P119_FM71_stim4']

In [9]:
# chargement des bad channels
bad_df = load_bad_channels_table(root_dir)
bad_df

           session             bad_channels
0   P64_BR34_stim2      B14,C15,GC6,GC7,W46
1   P97_BM50_stim1                     GC'4
2  P101_DC54_stim2       B_1,H_11,CU_12,Bp8
3  P101_DC54_stim4                      B_1
4  P119_FM71_stim4  Bp1,Bp2,Bp3,Bp6,Bp7,Bp8

##### Hilbert / une session

In [ ]:
session = sessions[0]

session_data = prepare_hilbert_session_data(
    session=session,
    root_dir=root_dir,
    bad_df=bad_df,
    cfg=hilbert_cfg,
) # crée le data_bp, le df avec infos stims, etc

In [16]:
# structure préparée
print("Session :", session_data["session"])
print("sfreq :", session_data["sfreq"])
# print("n_trials :", len(session_data["trials_df"]))
print("n_bipolar_channels :", len(session_data["bp_names"]))

session_data#["trials_df"][[
#     "label_stim",
#     "group_label",
#     "cog_labels",
#     "stim_shaft",
# ]]

Session : P119_FM71_stim4
sfreq : 512.0
n_bipolar_channels : 85

{'session': 'P119_FM71_stim4',
 'sfreq': 512.0,
 'stims_df':                       label_stim   t_start  duration         lobe  \
 0      Tp3-Tp42.0mA7.0Hz1025µsec   307.656   9.86499     L Insula
 1      Tp5-Tp62.0mA7.0Hz1025µsec   357.097   9.87872   L Temporal
 2      Tp8-Tp92.0mA7.0Hz1025µsec   391.859   9.88953   L Temporal
 3     Hp9-Hp102.0mA7.0Hz1025µsec   445.130   9.86789   L Temporal
 4      Hp5-Hp62.0mA7.0Hz1025µsec   474.216   9.86789   L Temporal
 5      Hp4-Hp52.0mA7.0Hz1025µsec   528.119   9.87872   L Temporal
 6      Hp1-Hp22.0mA7.0Hz1025µsec   604.054   9.88953   L Temporal
 7      Bp6-Bp72.0mA7.0Hz1025µsec   670.108   9.88953   L Temporal
 8     CP1-CP21.2mA50.0Hz1025µsec   927.946   4.99887  R Cingulate
 9       X7-X81.2mA50.0Hz1025µsec   996.349   4.98804     R Insula
 10      X5-X61.2mA50.0Hz1025µsec  1021.979   4.95560     R Insula
 11      X3-X41.2mA50.0Hz1025µsec  1046.349   4.93393     R Insula
 12      X3-X41.2mA50.0Hz1025µsec  1074.199   4.97720     R Insula
 13    FT4-FT51.2mA50.0Hz1025µsec  1139.619   4.98444    R Frontal
 14    FT7-FT81.2mA50.0Hz1025µsec  1194.149   4.99164    R Frontal
 15  CPp1-CPp21.5mA50.0Hz1025µsec  1285.059   4.99887  L Cingulate
 16  GCp1-GCp21.8mA50.0Hz1025µsec  1344.129   4.99887  L Cingulate
 17  CPp2-CPp32.0mA50.0Hz1025µsec  1464.869   4.99887  L Cingulate
 18  GCp2-GCp32.0mA50.0Hz1025µsec  1586.669   4.98444  L Cingulate
 19  CCp1-CCp22.0mA50.0Hz1025µsec  1652.709   4.99887  L Cingulate
 20    FT5-FT61.8mA50.0Hz1025µsec  1803.999   4.99887    L Frontal
 21  CPp1-CPp22.0mA50.0Hz1025µsec  1868.279   4.99887  L Cingulate
 22  GCp1-GCp22.2mA50.0Hz1025µsec  1975.689   5.00000  L Cingulate
 23  CPp2-CPp32.2mA50.0Hz1025µsec  2078.909   4.99167  L Cingulate
 24      H1-H21.8mA50.0Hz1025µsec  2224.449   4.99164     R Insula
 25    Tp2-Tp31.5mA50.0Hz1025µsec  2433.659   5.00610     L Insula
 26    Tp5-Tp61.5mA50.0Hz1025µsec  2468.249   4.97723   L Temporal
 27    Hp1-Hp21.5mA50.0Hz1025µsec  2496.289   4.98444     L Insula
 28    Yp6-Yp71.5mA50.0Hz1025µsec  2629.609   5.00610     L Insula
 29    Tp8-Tp91.5mA50.0Hz1025µsec  2783.949   4.98444   L Temporal
 30  OPp2-OPp31.5mA50.0Hz1025µsec  2826.379   4.98444     L Insula

                         cog group_label             cog_labels  stim_index  \
 0                       NaN     unknown                     []           0
 1                       NaN     unknown                     []           1
 2                       NaN     unknown                     []           2
 3                       NaN     unknown                     []           3
 4                       NaN     unknown                     []           4
 5                       NaN     unknown                     []           5
 6                       NaN     unknown                     []           6
 7                       NaN     unknown                     []           7
 8                       NaN     unknown                     []           8
 9                       NaN     unknown                     []           9
 10                      NaN     unknown                     []          10
 11                      NaN     unknown                     []          11
 12                      NaN     unknown                     []          12
 13                      NaN     unknown                     []          13
 14                      NaN     unknown                     []          14
 15             ['controle']    controle                     []          15
 16  ['illusion_perceptive']        cog+  [illusion_perceptive]          16
 17  ['illusion_perceptive']        cog+  [illusion_perceptive]          17
 18              ['negatif']     negatif                     []          18
 19                      NaN     unknown                     []          19
 20                      NaN     unknown                     []          20
 21                      NaN     unknown                     []          21
 22              ['negatif']     negatif                     []          22
 23  ['illusion_perceptive']        cog+  [illusion_perceptive]          23
 24                      NaN     unknown                     []          24
 25                      NaN     unknown                     []          25
 26                      NaN     unknown                     []          26
 27                      NaN     unknown                     []          27
 28                      NaN     unknown                     []          28
 29                      NaN     unknown                     []          29
 30                      NaN     unknown                     []          30

    stim_bipolar_label stim_shaft stim_contact_pair  stim_intensity  \
 0                None         Tp               3-4             2.0
 1                None         Tp               5-6             2.0
 2                None         Tp               8-9             2.0
 3                None         Hp              9-10             2.0
 4                None         Hp               5-6             2.0
 5                None         Hp               4-5             2.0
 6                None         Hp               1-2             2.0
 7                None         Bp               6-7             2.0
 8                None         CP               1-2             1.2
 9                None          X               7-8             1.2
 10               None          X               5-6             1.2
 11               None          X               3-4             1.2
 12               None          X               3-4             1.2
 13               None         FT               4-5             1.2
 14               None         FT               7-8             1.2
 15               None        CPp               1-2             1.5
 16               None        GCp               1-2             1.8
 17               None        CPp               2-3             2.0
 18               None        GCp               2-3             2.0
 19               None        CCp               1-2             2.0
 20               None         FT               5-6             1.8
 21               None        CPp               1-2             2.0
 22               None        GCp               1-2             2.2
 23               None        CPp               2-3             2.2
 24               None          H               1-2             1.8
 25               None         Tp               2-3             1.5
 26               None         Tp               5-6             1.5
 27               None         Hp               1-2             1.5
 28               None         Yp               6-7             1.5
 29               None         Tp               8-9             1.5
 30               None        OPp               2-3             1.5

     stim_frequency  pre_start   pre_end  post_start    post_end  stim_start  \
 0              7.0    304.556   307.556   317.62099   320.62099     307.656
 1              7.0    353.997   356.997   367.07572   370.07572     357.097
 2              7.0    388.759   391.759   401.84853   404.84853     391.859
 3              7.0    442.030   445.030   455.09789   458.09789     445.130
 4              7.0    471.116   474.116   484.18389   487.18389     474.216
 5              7.0    525.019   528.019   538.09772   541.09772     528.119
 6              7.0    600.954   603.954   614.04353   617.04353     604.054
 7              7.0    667.008   670.008   680.09753   683.09753     670.108
 8             50.0    924.846   927.846   933.04487   936.04487     927.946
 9             50.0    993.249   996.249  1001.43704  1004.43704     996.349
 10            50.0   1018.879  1021.879  1027.03460  1030.03460    1021.979
 11            50.0   1043.249  1046.249  1051.38293  1054.38293    1046.349
 12            50.0   1071.099  1074.099  1079.27620  1082.27620    1074.199
 13            50.0   1136.519  1139.519  1144.70344  1147.70344    1139.619
 14            50.0   1191.049  1194.049  1199.24064  1202.24064    1194.149
 15            50.0   1281.959  1284.959  1290.15787  1293.15787    1285.059
 16            50.0   1341.029  1344.029  1349.22787  1352.22787    1344.129
 17            50.0   1461.769  1464.769  1469.96787  1472.96787    1464.869
 18            50.0   1583.569  1586.569  1591.75344  1594.75344    1586.669
 19            50.0   1649.609  1652.609  1657.80787  1660.80787    1652.709
 20            50.0   1800.899  1803.899  1809.09787  1812.09787    1803.999
 21            50.0   1865.179  1868.179  1873.37787  1876.37787    1868.279
 22            50.0   1972.589  1975.589  1980.78900  1983.78900    1975.689
 23            50.0   2075.809  2078.809  2084.00067  2087.00067    2078.909
 24            50.0   2221.349  2224.349  2229.54064  2232.54064    2224.449
 25            50.0   2430.559  2433.559  2438.76510  2441.76510    2433.659
 26            50.0   2465.149  2468.149  2473.32623  2476.32623    2468.249
 27            50.0   2493.189  2496.189  2501.37344  2504.37344    2496.289
 28            50.0   2626.509  2629.509  2634.71510  2637.71510    2629.609
 29            50.0   2780.849  2783.849  2789.03344  2792.03344    2783.949
 30            50.0   2823.279  2826.279  2831.46344  2834.46344    2826.379

       stim_end
 0    317.52099
 1    366.97572
 2    401.74853
 3    454.99789
 4    484.08389
 5    537.99772
 6    613.94353
 7    679.99753
 8    932.94487
 9   1001.33704
 10  1026.93460
 11  1051.28293
 12  1079.17620
 13  1144.60344
 14  1199.14064
 15  1290.05787
 16  1349.12787
 17  1469.86787
 18  1591.65344
 19  1657.70787
 20  1808.99787
 21  1873.27787
 22  1980.68900
 23  2083.90067
 24  2229.44064
 25  2438.66510
 26  2473.22623
 27  2501.27344
 28  2634.61510
 29  2788.93344
 30  2831.36344  ,
 'raw_ch_names': ['TPp1',
  'TPp2',
  'TPp3',
  'TPp5',
  'TPp6',
  'Bp1',
  'Bp2',
  'Bp3',
  'Bp6',
  'Bp7',
  'Bp8',
  'Tp2',
  'Tp3',
  'Tp4',
  'Tp5',
  'Tp6',
  'Tp8',
  'Tp9',
  'Hp1',
  'Hp2',
  'Hp4',
  'Hp5',
  'Hp6',
  'Hp9',
  'Hp10',
  'Hp11',
  'ecg3+',
  'OFp1',
  'OFp2',
  'OFp3',
  'OFp5',
  'OFp6',
  'OFp8',
  'OFp9',
  'OPp2',
  'OPp3',
  'OPp4',
  'OPp6',
  'OPp7',
  'OPp9',
  'OPp10',
  'Xp1',
  'Xp2',
  'Xp3',
  'Xp4',
  'Xp5',
  'Xp7',
  'Xp8',
  'Xp9',
  'Xp10',
  'Xp11',
  'Xp16',
  'Xp17',
  'Xp18',
  'Yp1',
  'Yp2',
  'Yp3',
  'Yp4',
  'Yp5',
  'Yp6',
  'Yp7',
  'Yp8',
  'Yp9',
  'Yp10',
  'MKR1+',
  'FTp1',
  'FTp2',
  'FTp3',
  'FTp11',
  'FTp12',
  'FTp14',
  'FTp15',
  'FTp16',
  'CCp1',
  'CCp2',
  'CCp8',
  'CCp9',
  'CCp10',
  'CCp12',
  'CCp13',
  'CCp14',
  'CPp1',
  'CPp2',
  'CPp3',
  'CPp4',
  'CPp16',
  'CPp17',
  'GCp1',
  'GCp2',
  'GCp3',
  'GCp4',
  'GCp16',
  'GCp17',
  'FT1',
  'FT2',
  'FT3',
  'FT4',
  'FT5',
  'FT6',
  'FT7',
  'FT8',
  'FT9',
  'X1',
  'X2',
  'X3',
  'X4',
  'X5',
  'X6',
  'X7',
  'X8',
  'X10',
  'X13',
  'X14',
  'X16',
  'X17',
  'X18',
  'H1',
  'H2',
  'H3',
  'H4',
  'H6',
  'H7',
  'H8',
  'H9',
  'CP1',
  'CP2',
  'CP3',
  'CP5',
  'CP6',
  'thor+',
  'abdo+',
  'xyz+',
  'PULS+',
  'BEAT+',
  'SpO2+',
  'MKR2+'],
 'bad_channels': ['Bp1', 'Bp2', 'Bp3', 'Bp6', 'Bp7', 'Bp8'],
 'bp_names': ['TPp1-TPp2',
  'TPp2-TPp3',
  'TPp5-TPp6',
  'Tp2-Tp3',
  'Tp3-Tp4',
  'Tp4-Tp5',
  'Tp5-Tp6',
  'Tp8-Tp9',
  'Hp1-Hp2',
  'Hp4-Hp5',
  'Hp5-Hp6',
  'Hp9-Hp10',
  'Hp10-Hp11',
  'OFp1-OFp2',
  'OFp2-OFp3',
  'OFp5-OFp6',
  'OFp8-OFp9',
  'OPp2-OPp3',
  'OPp3-OPp4',
  'OPp6-OPp7',
  'OPp9-OPp10',
  'Xp1-Xp2',
  'Xp2-Xp3',
  'Xp3-Xp4',
  'Xp4-Xp5',
  'Xp7-Xp8',
  'Xp8-Xp9',
  'Xp9-Xp10',
  'Xp10-Xp11',
  'Xp16-Xp17',
  'Xp17-Xp18',
  'Yp1-Yp2',
  'Yp2-Yp3',
  'Yp3-Yp4',
  'Yp4-Yp5',
  'Yp5-Yp6',
  'Yp6-Yp7',
  'Yp7-Yp8',
  'Yp8-Yp9',
  'Yp9-Yp10',
  'FTp1-FTp2',
  'FTp2-FTp3',
  'FTp11-FTp12',
  'FTp14-FTp15',
  'FTp15-FTp16',
  'CCp1-CCp2',
  'CCp8-CCp9',
  'CCp9-CCp10',
  'CCp12-CCp13',
  'CCp13-CCp14',
  'CPp1-CPp2',
  'CPp2-CPp3',
  'CPp3-CPp4',
  'CPp16-CPp17',
  'GCp1-GCp2',
  'GCp2-GCp3',
  'GCp3-GCp4',
  'GCp16-GCp17',
  'FT1-FT2',
  'FT2-FT3',
  'FT3-FT4',
  'FT4-FT5',
  'FT5-FT6',
  'FT6-FT7',
  'FT7-FT8',
  'FT8-FT9',
  'X1-X2',
  'X2-X3',
  'X3-X4',
  'X4-X5',
  'X5-X6',
  'X6-X7',
  'X7-X8',
  'X13-X14',
  'X16-X17',
  'X17-X18',
  'H1-H2',
  'H2-H3',
  'H3-H4',
  'H6-H7',
  'H7-H8',
  'H8-H9',
  'CP1-CP2',
  'CP2-CP3',
  'CP5-CP6'],
 'data_bp': array([[ 1.27597952e-05,  1.27349910e-05,  1.66880060e-05, ...,
          4.68600408e-05,  4.24528957e-05,  3.90478714e-05],
        [ 1.87427667e-05,  2.21770884e-05,  2.24649075e-05, ...,
          3.14358123e-05,  3.06475912e-05,  2.70982194e-05],
        [-4.04751110e-06, -4.20320415e-06, -4.04506050e-06, ...,
          8.18480191e-06,  1.10816123e-05,  1.46265074e-05],
        ...,
        [-4.39162399e-05, -3.90804791e-05, -3.54114065e-05, ...,
         -3.08593667e-05, -2.52533620e-05, -1.60106281e-05],
        [-2.16691906e-05, -2.13888865e-05, -1.94566531e-05, ...,
         -3.59083708e-07, -5.73242959e-07, -2.58463057e-06],
        [ 3.93011079e-05,  4.73226926e-05,  5.00683805e-05, ...,
         -1.69260196e-05, -1.94498769e-05, -2.15589357e-05]],
       shape=(85, 3311104))}

In [ ]:
# run Hilbert sur cette session
session_out = run_session_hilbert( # 56 min sur une session à 15 stims (mais ensuite, 30 min pour une session à 30 stims...)
    session_data=session_data,
    out_dir=Path(hilbert_cfg.output_dir),
    cfg=hilbert_cfg,
)

session_out

=== Hilbert session P119_FM71_stim4 ===
[INFO] P119_FM71_stim4: facteur de décimation Hilbert = 8
[OK] P119_FM71_stim4: résultats Hilbert sauvegardés dans /home/aube/Documents/article_neuronal_stimic/effets_cog/LFP/theta_gamma_cog/results_hilbert/P119_FM71_stim4

PosixPath('/home/aube/Documents/article_neuronal_stimic/effets_cog/LFP/theta_gamma_cog/results_hilbert/P119_FM71_stim4')

In [19]:
# reload les exports Hilbert de cette session
exports = load_hilbert_session_exports(session_out)

print("Session exportée :", exports["session"])
print("times shape :", exports["times"].shape)
exports

Session exportée : P119_FM71_stim4
times shape : (384,)

{'session': 'P119_FM71_stim4',
 'metadata': {'session': 'P119_FM71_stim4',
  'config': {'root_dir': '/home/aube/Documents/article_neuronal_stimic/effets_cog/LFP/theta_gamma_cog',
   'output_dir': '/home/aube/Documents/article_neuronal_stimic/effets_cog/LFP/theta_gamma_cog/results_hilbert',
   'pre_length': 3.0,
   'post_length': 3.0,
   'epsilon': 0.1,
   'do_notch': True,
   'notch_freqs': [50.0, 100.0, 150.0],
   'notch_q': 30.0,
   'do_highpass': True,
   'highpass_hz': 0.1,
   'gamma_low_hz': 30.0,
   'gamma_high_hz': 150.0,
   'gamma_step_hz': 10.0,
   'beta_low_hz': 12.0,
   'beta_high_hz': 30.0,
   'beta_step_hz': 4.0,
   'alpha_low_hz': 8.0,
   'alpha_high_hz': 12.0,
   'alpha_step_hz': 2.0,
   'theta_low_hz': 4.0,
   'theta_high_hz': 8.0,
   'theta_step_hz': 2.0,
   'include_delta': False,
   'delta_low_hz': 1.0,
   'delta_high_hz': 4.0,
   'delta_step_hz': 1.0,
   'main_bands': ['delta',
    'theta',
    'alpha',
    'beta',
    'low_gamma',
    'high_gamma'],
   'low_gamma_split': [30.0, 80.0],
   'high_gamma_split': [80.0, 150.0],
   'alpha_range': [8.0, 12.0],
   'beta_range': [12.0, 30.0],
   'theta_range': [4.0, 8.0],
   'delta_range': [1.0, 4.0],
   'normalization_mode': 'pre_first_stim_mean',
   'eps': 1e-12,
   'target_dt_ms': 16.0,
   'save_subband_epochs': False,
   'save_main_band_epochs': True,
   'verbose': True},
  'n_trials': 31,
  'n_raw_channels': 136,
  'n_bad_channels': 6,
  'n_bipolar_channels': 85,
  'raw_ch_names': ['TPp1',
   'TPp2',
   'TPp3',
   'TPp5',
   'TPp6',
   'Bp1',
   'Bp2',
   'Bp3',
   'Bp6',
   'Bp7',
   'Bp8',
   'Tp2',
   'Tp3',
   'Tp4',
   'Tp5',
   'Tp6',
   'Tp8',
   'Tp9',
   'Hp1',
   'Hp2',
   'Hp4',
   'Hp5',
   'Hp6',
   'Hp9',
   'Hp10',
   'Hp11',
   'ecg3+',
   'OFp1',
   'OFp2',
   'OFp3',
   'OFp5',
   'OFp6',
   'OFp8',
   'OFp9',
   'OPp2',
   'OPp3',
   'OPp4',
   'OPp6',
   'OPp7',
   'OPp9',
   'OPp10',
   'Xp1',
   'Xp2',
   'Xp3',
   'Xp4',
   'Xp5',
   'Xp7',
   'Xp8',
   'Xp9',
   'Xp10',
   'Xp11',
   'Xp16',
   'Xp17',
   'Xp18',
   'Yp1',
   'Yp2',
   'Yp3',
   'Yp4',
   'Yp5',
   'Yp6',
   'Yp7',
   'Yp8',
   'Yp9',
   'Yp10',
   'MKR1+',
   'FTp1',
   'FTp2',
   'FTp3',
   'FTp11',
   'FTp12',
   'FTp14',
   'FTp15',
   'FTp16',
   'CCp1',
   'CCp2',
   'CCp8',
   'CCp9',
   'CCp10',
   'CCp12',
   'CCp13',
   'CCp14',
   'CPp1',
   'CPp2',
   'CPp3',
   'CPp4',
   'CPp16',
   'CPp17',
   'GCp1',
   'GCp2',
   'GCp3',
   'GCp4',
   'GCp16',
   'GCp17',
   'FT1',
   'FT2',
   'FT3',
   'FT4',
   'FT5',
   'FT6',
   'FT7',
   'FT8',
   'FT9',
   'X1',
   'X2',
   'X3',
   'X4',
   'X5',
   'X6',
   'X7',
   'X8',
   'X10',
   'X13',
   'X14',
   'X16',
   'X17',
   'X18',
   'H1',
   'H2',
   'H3',
   'H4',
   'H6',
   'H7',
   'H8',
   'H9',
   'CP1',
   'CP2',
   'CP3',
   'CP5',
   'CP6',
   'thor+',
   'abdo+',
   'xyz+',
   'PULS+',
   'BEAT+',
   'SpO2+',
   'MKR2+'],
  'bad_channels': ['Bp1', 'Bp2', 'Bp3', 'Bp6', 'Bp7', 'Bp8'],
  'bipolar_names': ['TPp1-TPp2',
   'TPp2-TPp3',
   'TPp5-TPp6',
   'Tp2-Tp3',
   'Tp3-Tp4',
   'Tp4-Tp5',
   'Tp5-Tp6',
   'Tp8-Tp9',
   'Hp1-Hp2',
   'Hp4-Hp5',
   'Hp5-Hp6',
   'Hp9-Hp10',
   'Hp10-Hp11',
   'OFp1-OFp2',
   'OFp2-OFp3',
   'OFp5-OFp6',
   'OFp8-OFp9',
   'OPp2-OPp3',
   'OPp3-OPp4',
   'OPp6-OPp7',
   'OPp9-OPp10',
   'Xp1-Xp2',
   'Xp2-Xp3',
   'Xp3-Xp4',
   'Xp4-Xp5',
   'Xp7-Xp8',
   'Xp8-Xp9',
   'Xp9-Xp10',
   'Xp10-Xp11',
   'Xp16-Xp17',
   'Xp17-Xp18',
   'Yp1-Yp2',
   'Yp2-Yp3',
   'Yp3-Yp4',
   'Yp4-Yp5',
   'Yp5-Yp6',
   'Yp6-Yp7',
   'Yp7-Yp8',
   'Yp8-Yp9',
   'Yp9-Yp10',
   'FTp1-FTp2',
   'FTp2-FTp3',
   'FTp11-FTp12',
   'FTp14-FTp15',
   'FTp15-FTp16',
   'CCp1-CCp2',
   'CCp8-CCp9',
   'CCp9-CCp10',
   'CCp12-CCp13',
   'CCp13-CCp14',
   'CPp1-CPp2',
   'CPp2-CPp3',
   'CPp3-CPp4',
   'CPp16-CPp17',
   'GCp1-GCp2',
   'GCp2-GCp3',
   'GCp3-GCp4',
   'GCp16-GCp17',
   'FT1-FT2',
   'FT2-FT3',
   'FT3-FT4',
   'FT4-FT5',
   'FT5-FT6',
   'FT6-FT7',
   'FT7-FT8',
   'FT8-FT9',
   'X1-X2',
   'X2-X3',
   'X3-X4',
   'X4-X5',
   'X5-X6',
   'X6-X7',
   'X7-X8',
   'X13-X14',
   'X16-X17',
   'X17-X18',
   'H1-H2',
   'H2-H3',
   'H3-H4',
   'H6-H7',
   'H7-H8',
   'H8-H9',
   'CP1-CP2',
   'CP2-CP3',
   'CP5-CP6'],
  'main_band_to_subbands': {'theta': [{'family': 'theta',
     'f_low': 4.0,
     'f_high': 6.0},
    {'family': 'theta', 'f_low': 6.0, 'f_high': 8.0}],
   'alpha': [{'family': 'alpha', 'f_low': 8.0, 'f_high': 10.0},
    {'family': 'alpha', 'f_low': 10.0, 'f_high': 12.0}],
   'beta': [{'family': 'beta', 'f_low': 12.0, 'f_high': 16.0},
    {'family': 'beta', 'f_low': 16.0, 'f_high': 20.0},
    {'family': 'beta', 'f_low': 20.0, 'f_high': 24.0},
    {'family': 'beta', 'f_low': 24.0, 'f_high': 28.0},
    {'family': 'beta', 'f_low': 28.0, 'f_high': 30.0}],
   'low_gamma': [{'family': 'gamma', 'f_low': 30.0, 'f_high': 40.0},
    {'family': 'gamma', 'f_low': 40.0, 'f_high': 50.0},
    {'family': 'gamma', 'f_low': 50.0, 'f_high': 60.0},
    {'family': 'gamma', 'f_low': 60.0, 'f_high': 70.0},
    {'family': 'gamma', 'f_low': 70.0, 'f_high': 80.0}],
   'high_gamma': [{'family': 'gamma', 'f_low': 80.0, 'f_high': 90.0},
    {'family': 'gamma', 'f_low': 90.0, 'f_high': 100.0},
    {'family': 'gamma', 'f_low': 100.0, 'f_high': 110.0},
    {'family': 'gamma', 'f_low': 110.0, 'f_high': 120.0},
    {'family': 'gamma', 'f_low': 120.0, 'f_high': 130.0},
    {'family': 'gamma', 'f_low': 130.0, 'f_high': 140.0},
    {'family': 'gamma', 'f_low': 140.0, 'f_high': 150.0}]}},
 'stims_df':                       label_stim   t_start  duration         lobe  \
 0      Tp3-Tp42.0mA7.0Hz1025µsec   307.656   9.86499     L Insula
 1      Tp5-Tp62.0mA7.0Hz1025µsec   357.097   9.87872   L Temporal
 2      Tp8-Tp92.0mA7.0Hz1025µsec   391.859   9.88953   L Temporal
 3     Hp9-Hp102.0mA7.0Hz1025µsec   445.130   9.86789   L Temporal
 4      Hp5-Hp62.0mA7.0Hz1025µsec   474.216   9.86789   L Temporal
 5      Hp4-Hp52.0mA7.0Hz1025µsec   528.119   9.87872   L Temporal
 6      Hp1-Hp22.0mA7.0Hz1025µsec   604.054   9.88953   L Temporal
 7      Bp6-Bp72.0mA7.0Hz1025µsec   670.108   9.88953   L Temporal
 8     CP1-CP21.2mA50.0Hz1025µsec   927.946   4.99887  R Cingulate
 9       X7-X81.2mA50.0Hz1025µsec   996.349   4.98804     R Insula
 10      X5-X61.2mA50.0Hz1025µsec  1021.979   4.95560     R Insula
 11      X3-X41.2mA50.0Hz1025µsec  1046.349   4.93393     R Insula
 12      X3-X41.2mA50.0Hz1025µsec  1074.199   4.97720     R Insula
 13    FT4-FT51.2mA50.0Hz1025µsec  1139.619   4.98444    R Frontal
 14    FT7-FT81.2mA50.0Hz1025µsec  1194.149   4.99164    R Frontal
 15  CPp1-CPp21.5mA50.0Hz1025µsec  1285.059   4.99887  L Cingulate
 16  GCp1-GCp21.8mA50.0Hz1025µsec  1344.129   4.99887  L Cingulate
 17  CPp2-CPp32.0mA50.0Hz1025µsec  1464.869   4.99887  L Cingulate
 18  GCp2-GCp32.0mA50.0Hz1025µsec  1586.669   4.98444  L Cingulate
 19  CCp1-CCp22.0mA50.0Hz1025µsec  1652.709   4.99887  L Cingulate
 20    FT5-FT61.8mA50.0Hz1025µsec  1803.999   4.99887    L Frontal
 21  CPp1-CPp22.0mA50.0Hz1025µsec  1868.279   4.99887  L Cingulate
 22  GCp1-GCp22.2mA50.0Hz1025µsec  1975.689   5.00000  L Cingulate
 23  CPp2-CPp32.2mA50.0Hz1025µsec  2078.909   4.99167  L Cingulate
 24      H1-H21.8mA50.0Hz1025µsec  2224.449   4.99164     R Insula
 25    Tp2-Tp31.5mA50.0Hz1025µsec  2433.659   5.00610     L Insula
 26    Tp5-Tp61.5mA50.0Hz1025µsec  2468.249   4.97723   L Temporal
 27    Hp1-Hp21.5mA50.0Hz1025µsec  2496.289   4.98444     L Insula
 28    Yp6-Yp71.5mA50.0Hz1025µsec  2629.609   5.00610     L Insula
 29    Tp8-Tp91.5mA50.0Hz1025µsec  2783.949   4.98444   L Temporal
 30  OPp2-OPp31.5mA50.0Hz1025µsec  2826.379   4.98444     L Insula

                         cog group_label               cog_labels  stim_index  \
 0                       NaN     unknown                       []           0
 1                       NaN     unknown                       []           1
 2                       NaN     unknown                       []           2
 3                       NaN     unknown                       []           3
 4                       NaN     unknown                       []           4
 5                       NaN     unknown                       []           5
 6                       NaN     unknown                       []           6
 7                       NaN     unknown                       []           7
 8                       NaN     unknown                       []           8
 9                       NaN     unknown                       []           9
 10                      NaN     unknown                       []          10
 11                      NaN     unknown                       []          11
 12                      NaN     unknown                       []          12
 13                      NaN     unknown                       []          13
 14                      NaN     unknown                       []          14
 15             ['controle']    controle                       []          15
 16  ['illusion_perceptive']        cog+  ['illusion_perceptive']          16
 17  ['illusion_perceptive']        cog+  ['illusion_perceptive']          17
 18              ['negatif']     negatif                       []          18
 19                      NaN     unknown                       []          19
 20                      NaN     unknown                       []          20
 21                      NaN     unknown                       []          21
 22              ['negatif']     negatif                       []          22
 23  ['illusion_perceptive']        cog+  ['illusion_perceptive']          23
 24                      NaN     unknown                       []          24
 25                      NaN     unknown                       []          25
 26                      NaN     unknown                       []          26
 27                      NaN     unknown                       []          27
 28                      NaN     unknown                       []          28
 29                      NaN     unknown                       []          29
 30                      NaN     unknown                       []          30

     stim_bipolar_label stim_shaft stim_contact_pair  stim_intensity  \
 0                  NaN         Tp               3-4             2.0
 1                  NaN         Tp               5-6             2.0
 2                  NaN         Tp               8-9             2.0
 3                  NaN         Hp              9-10             2.0
 4                  NaN         Hp               5-6             2.0
 5                  NaN         Hp               4-5             2.0
 6                  NaN         Hp               1-2             2.0
 7                  NaN         Bp               6-7             2.0
 8                  NaN         CP               1-2             1.2
 9                  NaN          X               7-8             1.2
 10                 NaN          X               5-6             1.2
 11                 NaN          X               3-4             1.2
 12                 NaN          X               3-4             1.2
 13                 NaN         FT               4-5             1.2
 14                 NaN         FT               7-8             1.2
 15                 NaN        CPp               1-2             1.5
 16                 NaN        GCp               1-2             1.8
 17                 NaN        CPp               2-3             2.0
 18                 NaN        GCp               2-3             2.0
 19                 NaN        CCp               1-2             2.0
 20                 NaN         FT               5-6             1.8
 21                 NaN        CPp               1-2             2.0
 22                 NaN        GCp               1-2             2.2
 23                 NaN        CPp               2-3             2.2
 24                 NaN          H               1-2             1.8
 25                 NaN         Tp               2-3             1.5
 26                 NaN         Tp               5-6             1.5
 27                 NaN         Hp               1-2             1.5
 28                 NaN         Yp               6-7             1.5
 29                 NaN         Tp               8-9             1.5
 30                 NaN        OPp               2-3             1.5

     stim_frequency  pre_start   pre_end  post_start    post_end  stim_start  \
 0              7.0    304.556   307.556   317.62099   320.62099     307.656
 1              7.0    353.997   356.997   367.07572   370.07572     357.097
 2              7.0    388.759   391.759   401.84853   404.84853     391.859
 3              7.0    442.030   445.030   455.09789   458.09789     445.130
 4              7.0    471.116   474.116   484.18389   487.18389     474.216
 5              7.0    525.019   528.019   538.09772   541.09772     528.119
 6              7.0    600.954   603.954   614.04353   617.04353     604.054
 7              7.0    667.008   670.008   680.09753   683.09753     670.108
 8             50.0    924.846   927.846   933.04487   936.04487     927.946
 9             50.0    993.249   996.249  1001.43704  1004.43704     996.349
 10            50.0   1018.879  1021.879  1027.03460  1030.03460    1021.979
 11            50.0   1043.249  1046.249  1051.38293  1054.38293    1046.349
 12            50.0   1071.099  1074.099  1079.27620  1082.27620    1074.199
 13            50.0   1136.519  1139.519  1144.70344  1147.70344    1139.619
 14            50.0   1191.049  1194.049  1199.24064  1202.24064    1194.149
 15            50.0   1281.959  1284.959  1290.15787  1293.15787    1285.059
 16            50.0   1341.029  1344.029  1349.22787  1352.22787    1344.129
 17            50.0   1461.769  1464.769  1469.96787  1472.96787    1464.869
 18            50.0   1583.569  1586.569  1591.75344  1594.75344    1586.669
 19            50.0   1649.609  1652.609  1657.80787  1660.80787    1652.709
 20            50.0   1800.899  1803.899  1809.09787  1812.09787    1803.999
 21            50.0   1865.179  1868.179  1873.37787  1876.37787    1868.279
 22            50.0   1972.589  1975.589  1980.78900  1983.78900    1975.689
 23            50.0   2075.809  2078.809  2084.00067  2087.00067    2078.909
 24            50.0   2221.349  2224.349  2229.54064  2232.54064    2224.449
 25            50.0   2430.559  2433.559  2438.76510  2441.76510    2433.659
 26            50.0   2465.149  2468.149  2473.32623  2476.32623    2468.249
 27            50.0   2493.189  2496.189  2501.37344  2504.37344    2496.289
 28            50.0   2626.509  2629.509  2634.71510  2637.71510    2629.609
 29            50.0   2780.849  2783.849  2789.03344  2792.03344    2783.949
 30            50.0   2823.279  2826.279  2831.46344  2834.46344    2826.379

       stim_end
 0    317.52099
 1    366.97572
 2    401.74853
 3    454.99789
 4    484.08389
 5    537.99772
 6    613.94353
 7    679.99753
 8    932.94487
 9   1001.33704
 10  1026.93460
 11  1051.28293
 12  1079.17620
 13  1144.60344
 14  1199.14064
 15  1290.05787
 16  1349.12787
 17  1469.86787
 18  1591.65344
 19  1657.70787
 20  1808.99787
 21  1873.27787
 22  1980.68900
 23  2083.90067
 24  2229.44064
 25  2438.66510
 26  2473.22623
 27  2501.27344
 28  2634.61510
 29  2788.93344
 30  2831.36344  ,
 'times': array([-3.      , -2.984375, -2.96875 , -2.953125, -2.9375  , -2.921875,
        -2.90625 , -2.890625, -2.875   , -2.859375, -2.84375 , -2.828125,
        -2.8125  , -2.796875, -2.78125 , -2.765625, -2.75    , -2.734375,
        -2.71875 , -2.703125, -2.6875  , -2.671875, -2.65625 , -2.640625,
        -2.625   , -2.609375, -2.59375 , -2.578125, -2.5625  , -2.546875,
        -2.53125 , -2.515625, -2.5     , -2.484375, -2.46875 , -2.453125,
        -2.4375  , -2.421875, -2.40625 , -2.390625, -2.375   , -2.359375,
        -2.34375 , -2.328125, -2.3125  , -2.296875, -2.28125 , -2.265625,
        -2.25    , -2.234375, -2.21875 , -2.203125, -2.1875  , -2.171875,
        -2.15625 , -2.140625, -2.125   , -2.109375, -2.09375 , -2.078125,
        -2.0625  , -2.046875, -2.03125 , -2.015625, -2.      , -1.984375,
        -1.96875 , -1.953125, -1.9375  , -1.921875, -1.90625 , -1.890625,
        -1.875   , -1.859375, -1.84375 , -1.828125, -1.8125  , -1.796875,
        -1.78125 , -1.765625, -1.75    , -1.734375, -1.71875 , -1.703125,
        -1.6875  , -1.671875, -1.65625 , -1.640625, -1.625   , -1.609375,
        -1.59375 , -1.578125, -1.5625  , -1.546875, -1.53125 , -1.515625,
        -1.5     , -1.484375, -1.46875 , -1.453125, -1.4375  , -1.421875,
        -1.40625 , -1.390625, -1.375   , -1.359375, -1.34375 , -1.328125,
        -1.3125  , -1.296875, -1.28125 , -1.265625, -1.25    , -1.234375,
        -1.21875 , -1.203125, -1.1875  , -1.171875, -1.15625 , -1.140625,
        -1.125   , -1.109375, -1.09375 , -1.078125, -1.0625  , -1.046875,
        -1.03125 , -1.015625, -1.      , -0.984375, -0.96875 , -0.953125,
        -0.9375  , -0.921875, -0.90625 , -0.890625, -0.875   , -0.859375,
        -0.84375 , -0.828125, -0.8125  , -0.796875, -0.78125 , -0.765625,
        -0.75    , -0.734375, -0.71875 , -0.703125, -0.6875  , -0.671875,
        -0.65625 , -0.640625, -0.625   , -0.609375, -0.59375 , -0.578125,
        -0.5625  , -0.546875, -0.53125 , -0.515625, -0.5     , -0.484375,
        -0.46875 , -0.453125, -0.4375  , -0.421875, -0.40625 , -0.390625,
        -0.375   , -0.359375, -0.34375 , -0.328125, -0.3125  , -0.296875,
        -0.28125 , -0.265625, -0.25    , -0.234375, -0.21875 , -0.203125,
        -0.1875  , -0.171875, -0.15625 , -0.140625, -0.125   , -0.109375,
        -0.09375 , -0.078125, -0.0625  , -0.046875, -0.03125 , -0.015625,
         0.      ,  0.015625,  0.03125 ,  0.046875,  0.0625  ,  0.078125,
         0.09375 ,  0.109375,  0.125   ,  0.140625,  0.15625 ,  0.171875,
         0.1875  ,  0.203125,  0.21875 ,  0.234375,  0.25    ,  0.265625,
         0.28125 ,  0.296875,  0.3125  ,  0.328125,  0.34375 ,  0.359375,
         0.375   ,  0.390625,  0.40625 ,  0.421875,  0.4375  ,  0.453125,
         0.46875 ,  0.484375,  0.5     ,  0.515625,  0.53125 ,  0.546875,
         0.5625  ,  0.578125,  0.59375 ,  0.609375,  0.625   ,  0.640625,
         0.65625 ,  0.671875,  0.6875  ,  0.703125,  0.71875 ,  0.734375,
         0.75    ,  0.765625,  0.78125 ,  0.796875,  0.8125  ,  0.828125,
         0.84375 ,  0.859375,  0.875   ,  0.890625,  0.90625 ,  0.921875,
         0.9375  ,  0.953125,  0.96875 ,  0.984375,  1.      ,  1.015625,
         1.03125 ,  1.046875,  1.0625  ,  1.078125,  1.09375 ,  1.109375,
         1.125   ,  1.140625,  1.15625 ,  1.171875,  1.1875  ,  1.203125,
         1.21875 ,  1.234375,  1.25    ,  1.265625,  1.28125 ,  1.296875,
         1.3125  ,  1.328125,  1.34375 ,  1.359375,  1.375   ,  1.390625,
         1.40625 ,  1.421875,  1.4375  ,  1.453125,  1.46875 ,  1.484375,
         1.5     ,  1.515625,  1.53125 ,  1.546875,  1.5625  ,  1.578125,
         1.59375 ,  1.609375,  1.625   ,  1.640625,  1.65625 ,  1.671875,
         1.6875  ,  1.703125,  1.71875 ,  1.734375,  1.75    ,  1.765625,
         1.78125 ,  1.796875,  1.8125  ,  1.828125,  1.84375 ,  1.859375,
         1.875   ,  1.890625,  1.90625 ,  1.921875,  1.9375  ,  1.953125,
         1.96875 ,  1.984375,  2.      ,  2.015625,  2.03125 ,  2.046875,
         2.0625  ,  2.078125,  2.09375 ,  2.109375,  2.125   ,  2.140625,
         2.15625 ,  2.171875,  2.1875  ,  2.203125,  2.21875 ,  2.234375,
         2.25    ,  2.265625,  2.28125 ,  2.296875,  2.3125  ,  2.328125,
         2.34375 ,  2.359375,  2.375   ,  2.390625,  2.40625 ,  2.421875,
         2.4375  ,  2.453125,  2.46875 ,  2.484375,  2.5     ,  2.515625,
         2.53125 ,  2.546875,  2.5625  ,  2.578125,  2.59375 ,  2.609375,
         2.625   ,  2.640625,  2.65625 ,  2.671875,  2.6875  ,  2.703125,
         2.71875 ,  2.734375,  2.75    ,  2.765625,  2.78125 ,  2.796875,

In [20]:
# reload une bande Hilbert de la session
band_name = "low_gamma"
arr = load_hilbert_band_epochs(session_out, exports["session"], band_name)
print(arr.shape)   # attendu : (n_trials, n_channels, n_times)

(31, 85, 384)

##### Hilbert / toutes les sessions

In [6]:
summary_hilbert = run_all_sessions_hilbert(hilbert_cfg) # 243 min pour 2 sessions avec 60n de stims
summary_hilbert

1 sessions TRC trouvées pour Hilbert

=== Préparation Hilbert session P101_DC54_stim2 ===

WARNING:root:MKR channel(s) is not close to 50mV. If no trigger received, then data are corrupted.

[INFO] P101_DC54_stim2.TRC: sfreq = 2048.0
[INFO] P101_DC54_stim2.TRC: unités canal détectées = ['%', 'bpm', 'dimentionless', 'μV']

=== Hilbert session P101_DC54_stim2 ===
[INFO] P101_DC54_stim2: facteur de décimation Hilbert = 33
[OK] P101_DC54_stim2: résultats Hilbert sauvegardés dans /home/aube/Documents/article_neuronal_stimic/effets_cog/theta_gamma_cog/results_hilbert/P101_DC54_stim2

{'config': {'root_dir': '/home/aube/Documents/article_neuronal_stimic/effets_cog/theta_gamma_cog',
  'output_dir': '/home/aube/Documents/article_neuronal_stimic/effets_cog/theta_gamma_cog/results_hilbert',
  'pre_length': 3.0,
  'post_length': 3.0,
  'epsilon': 0.1,
  'do_notch': True,
  'notch_freqs': (50.0, 100.0, 150.0),
  'notch_q': 30.0,
  'do_highpass': True,
  'highpass_hz': 0.1,
  'gamma_low_hz': 30.0,
  'gamma_high_hz': 150.0,
  'gamma_step_hz': 10.0,
  'beta_low_hz': 12.0,
  'beta_high_hz': 30.0,
  'beta_step_hz': 4.0,
  'alpha_low_hz': 8.0,
  'alpha_high_hz': 12.0,
  'alpha_step_hz': 2.0,
  'theta_low_hz': 4.0,
  'theta_high_hz': 8.0,
  'theta_step_hz': 2.0,
  'include_delta': False,
  'delta_low_hz': 1.0,
  'delta_high_hz': 4.0,
  'delta_step_hz': 1.0,
  'main_bands': ('delta', 'theta', 'alpha', 'beta', 'low_gamma', 'high_gamma'),
  'low_gamma_split': (30.0, 80.0),
  'high_gamma_split': (80.0, 150.0),
  'alpha_range': (8.0, 12.0),
  'beta_range': (12.0, 30.0),
  'theta_range': (4.0, 8.0),
  'delta_range': (1.0, 4.0),
  'normalization_mode': 'pre_first_stim_mean',
  'eps': 1e-12,
  'target_dt_ms': 16.0,
  'save_subband_epochs': False,
  'save_main_band_epochs': True,
  'verbose': True},
 'n_sessions': 1,
 'n_errors': 0,
 'errors': []}

In [ ]:
# lecture des résumés produits
summary_file = Path(hilbert_cfg.output_root) / "run_summary_hilbert.json"
with open(summary_file, "r") as f:
    summary = json.load(f)
summary

#### Stats sur Hilbert

Structure de travail : 

results_hilbert/                                                     {= input_root, dans HilbertStatsConfig}
    └── PATIENT_stimN/                                               {nécessaire}
        ├── PATIENT_stimN_metadata.json
        ├── PATIENT_stimN_trial_table.csv
        ├── PATIENT_stimN_times.npy
        └── PATIENT_stimN_hilbert_<band>.npy {theta, alpha, beta, low_gamma}
    ...
    └── run_summary_hilbert.json                                     {nécessaire}


├── results_hilbert_stats/                                           {= output_root, dans HilbertStatsConfig}
    └── pooled_across_sessions/                                      {créé}
        ├── condition_main/
            ├── negatif/
                ├── distant/
                    ...
                    └── <band>
                        ├── cluster_pvals.npy
                        ├── mean_trace.npy
                        ├── median_trace.npy
                        ├── pvals_wilcoxon.npy
                        ├── pvals_wilcoxon_fdr.npy
                        ├── sig_mask_cluster.npy
                        ├── sig_mask_wilcoxon_fdr.npy
                        ├── stat_wilcoxon.npy
                        ├── T_obs_cluster.npy
                        ├── observations_table.csv
                        ├── figure_cluster.png
                        └── figure_wilcoxon.png
                └── local
                    ...idem que distant
            ...
        ├── condition_subcategories/
            ...idem que condition_main
        ├── hilbert_stats_config.json
        └── summary_hilbert_stats.csv
    ...
    └── run_summary_hilbert.json                                     {créé}

In [2]:
# configuration stats

hilbert_stats_cfg = HilbertStatsConfig(
    input_root="/home/aube/Documents/article_neuronal_stimic/effets_cog/LFP/theta_gamma_cog/results_hilbert",
    output_root="/home/aube/Documents/article_neuronal_stimic/effets_cog/LFP/theta_gamma_cog/results_hilbert_stats",

    bands_to_test=("theta", "alpha", "beta", "low_gamma", "high_gamma"),

    run_wilcoxon_fdr=True,
    run_cluster_perm=True,
    alpha_fdr=0.05,

    cluster_alpha=0.05,
    n_permutations=2000,
    cluster_threshold_p=0.05,
    tail=0,
    seed=13,

    min_trials_per_condition=3,
    make_main_groups=True,
    make_cog_subgroups=True,
    keep_main_groups_in_subgroup_mode=True,
    localities_to_test=("local", "distant"),

    group_across_sessions=True,
    also_run_per_session=False,
    pooled_output_subdir="pooled_across_sessions",

    save_figures=True,
    figure_dpi=150,
    verbose=True,
)

##### sur une session

In [3]:
# screen des conditions d'une session Hilbert
session_dir = sorted([p for p in Path(hilbert_stats_cfg.input_root).iterdir() if p.is_dir()])[1]
session = session_dir.name
trials_df = pd.read_csv(session_dir / f"{session}_trial_table.csv")

cond_index_main = build_main_condition_index(trials_df, min_trials=hilbert_stats_cfg.min_trials_per_condition)
cond_index_sub = build_cog_subcategory_index(
    trials_df,
    min_trials=hilbert_stats_cfg.min_trials_per_condition,
    keep_main_groups=hilbert_stats_cfg.keep_main_groups_in_subgroup_mode,
)

print({k: len(v) for k, v in cond_index_main.items()})
print({k: len(v) for k, v in cond_index_sub.items()})

{'cog+': 3}
{'cog+': 3, 'cog::illusion_perceptive': 3}

In [25]:
# test d'empilage de Hilbert sur une session
meta = json.load(open(session_dir / f"{session}_metadata.json", "r", encoding="utf-8"))
bp_names = meta["bipolar_names"]

condition_name = list(cond_index_main.keys())[0]
trial_indices = cond_index_main[condition_name]

X_local, obs_local = stack_hilbert_band_condition_locality(
    session=session,
    session_dir=session_dir,
    trials_df=trials_df,
    bp_names=bp_names,
    trial_indices=trial_indices,
    locality="local",
    band_name="low_gamma",
    condition_name=condition_name,
)

print(X_local.shape)   # attendu : (n_observations, n_times)
obs_local.head()

(38, 373)

,session,condition,trial_idx,channel_name,channel_shaft,stim_shaft,label_stim,group_label,cog_labels,locality,band_name
0,P101_DC54_stim2,negatif,31,C1-C2,C,C,C_1-C_22.0mA7.0Hz1025µsec,negatif,[],local,low_gamma
1,P101_DC54_stim2,negatif,31,C2-C3,C,C,C_1-C_22.0mA7.0Hz1025µsec,negatif,[],local,low_gamma
2,P101_DC54_stim2,negatif,31,C3-C4,C,C,C_1-C_22.0mA7.0Hz1025µsec,negatif,[],local,low_gamma
3,P101_DC54_stim2,negatif,31,C4-C5,C,C,C_1-C_22.0mA7.0Hz1025µsec,negatif,[],local,low_gamma
4,P101_DC54_stim2,negatif,31,C5-C6,C,C,C_1-C_22.0mA7.0Hz1025µsec,negatif,[],local,low_gamma

In [ ]:
# stats Hilbert sur une seule session
out_session_stats = run_hilbert_session_condition_stats(
    session_dir=session_dir,
    cfg=hilbert_stats_cfg,
)

out_session_stats

NameError: name 'session_dir' is not defined

##### sur toutes les sessions

In [4]:
# test d'empilage de Hilbert pooled across sessions

session_dirs = sorted([p for p in Path(hilbert_stats_cfg.input_root).iterdir() if p.is_dir()])

X_all, obs_all = stack_hilbert_band_condition_locality_across_sessions(
    session_dirs=session_dirs,
    condition_name="cog+",
    locality="distant",
    band_name="theta",
    cfg=hilbert_stats_cfg,
    subgroup_mode=False,
)

print("X_all shape :", X_all.shape)
print("n sessions :", obs_all["session"].nunique())
print("n unique trials :", obs_all[["session", "trial_idx"]].drop_duplicates().shape[0])
print("n unique channels :", obs_all[["session", "channel_name"]].drop_duplicates().shape[0])

obs_all.head()

X_all shape : (243, 384)
n sessions : 1
n unique trials : 3
n unique channels : 85

,session,condition,trial_idx,channel_name,channel_shaft,stim_shaft,label_stim,group_label,cog_labels,locality,band_name
0,P119_FM71_stim4,cog+,16,TPp1-TPp2,TPp,GCp,GCp1-GCp21.8mA50.0Hz1025µsec,cog+,['illusion_perceptive'],distant,theta
1,P119_FM71_stim4,cog+,17,TPp1-TPp2,TPp,CPp,CPp2-CPp32.0mA50.0Hz1025µsec,cog+,['illusion_perceptive'],distant,theta
2,P119_FM71_stim4,cog+,23,TPp1-TPp2,TPp,CPp,CPp2-CPp32.2mA50.0Hz1025µsec,cog+,['illusion_perceptive'],distant,theta
3,P119_FM71_stim4,cog+,16,TPp2-TPp3,TPp,GCp,GCp1-GCp21.8mA50.0Hz1025µsec,cog+,['illusion_perceptive'],distant,theta
4,P119_FM71_stim4,cog+,17,TPp2-TPp3,TPp,CPp,CPp2-CPp32.0mA50.0Hz1025µsec,cog+,['illusion_perceptive'],distant,theta

In [5]:
# stats Hilbert pooled across sessions
out_pooled_stats = run_pooled_hilbert_condition_stats(hilbert_stats_cfg)
out_pooled_stats

/var/data/python/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

PosixPath('/home/aube/Documents/article_neuronal_stimic/effets_cog/LFP/theta_gamma_cog/results_hilbert_stats/pooled_across_sessions')

In [6]:
# point d'entrée global des stats Hilbert : lance run_pooled_hilbert_condition_stats et/ou run_hilbert_session_condition_stats par session, selon le cfg
summary_hilbert_stats = run_all_hilbert_stats(hilbert_stats_cfg)
summary_hilbert_stats

{'config': {'input_root': '/home/aube/Documents/article_neuronal_stimic/effets_cog/LFP/theta_gamma_cog/results_hilbert',
  'output_root': '/home/aube/Documents/article_neuronal_stimic/effets_cog/LFP/theta_gamma_cog/results_hilbert_stats',
  'bands_to_test': ('theta', 'alpha', 'beta', 'low_gamma', 'high_gamma'),
  'run_wilcoxon_fdr': True,
  'run_cluster_perm': True,
  'alpha_fdr': 0.05,
  'cluster_alpha': 0.05,
  'n_permutations': 2000,
  'cluster_threshold_p': 0.05,
  'tail': 0,
  'seed': 13,
  'min_trials_per_condition': 3,
  'make_main_groups': True,
  'make_cog_subgroups': True,
  'keep_main_groups_in_subgroup_mode': True,
  'localities_to_test': ('local', 'distant'),
  'group_across_sessions': True,
  'also_run_per_session': False,
  'pooled_output_subdir': 'pooled_across_sessions',
  'save_figures': True,
  'figure_dpi': 150,
  'verbose': True},
 'n_errors': 0,
 'errors': []}

In [ ]:
# lecture des résumés produits
summary_file = Path(hilbert_stats_cfg.output_root) / "run_summary_hilbert_stats.json"
with open(summary_file, "r") as f:
    summary = json.load(f)
summary

{'config': {'input_root': '/home/aube/Documents/article_neuronal_stimic/effets_cog/LFP/theta_gamma_cog/results_hilbert',
  'output_root': '/home/aube/Documents/article_neuronal_stimic/effets_cog/LFP/theta_gamma_cog/results_hilbert_stats',
  'bands_to_test': ['theta', 'alpha', 'beta', 'low_gamma', 'high_gamma'],
  'run_wilcoxon_fdr': True,
  'run_cluster_perm': True,
  'alpha_fdr': 0.05,
  'cluster_alpha': 0.05,
  'n_permutations': 2000,
  'cluster_threshold_p': 0.05,
  'tail': 0,
  'seed': 13,
  'min_trials_per_condition': 3,
  'make_main_groups': True,
  'make_cog_subgroups': True,
  'keep_main_groups_in_subgroup_mode': True,
  'localities_to_test': ['local', 'distant'],
  'group_across_sessions': True,
  'also_run_per_session': False,
  'pooled_output_subdir': 'pooled_across_sessions',
  'save_figures': True,
  'figure_dpi': 150,
  'verbose': True},
 'n_errors': 0,
 'errors': []}